dependencies {
    implementation(project(path: ":embulk-input-jdbc", configuration: "runtimeElements"))

    compileOnly "com.mysql:mysql-connector-j:9.6.0"
    defaultJdbcDriver 'com.mysql:mysql-connector-j:9.6.0'

    testImplementation "com.google.guava:guava:18.0"
    testImplementation "org.embulk:embulk-formatter-csv:0.11.1"
    testImplementation "org.embulk:embulk-input-file:0.11.0"
    testImplementation "org.embulk:embulk-output-file:0.11.0"
    testImplementation "org.embulk:embulk-parser-csv:0.11.3"

    testImplementation "com.mysql:mysql-connector-j:9.6.0"
}

embulkPlugin {
    mainClass = "org.embulk.input.mysql.MySQLInputPlugin"
    category = "input"
    type = "mysql"
    additionalDependencyDeclarations = [
        [ groupId: "com.mysql", artifactId: "mysql-connector-j", version: "9.6.0", scope: "compile", optional: true ],
    ]
}

publishing {
    publications {
        maven(MavenPublication) {
            pom {  // https://central.sonatype.org/pages/requirements.html
                developers {
                    developer {
                        name = "Sadayuki Furuhashi"
                        email = "frsyuki@gmail.com"
                    }
                    developer {
                        name = "Hitoshi Tanaka"
                        email = "thitoshi@cac.co.jp"
                    }
                    developer {
                        name = "Muga Nishizawa"
                        email = "muga.nishizawa@gmail.com"
                    }
                    developer {
                        name = "Hiroyuki Sato"
                        email = "hiroysato@gmail.com"
                    }
                    developer {
                        name = "Dai MIKURUBE"
                        email = "dmikurube@treasure-data.com"
                    }
                    developer {
                        name = "Robert Nguyen"
                        email = "ng.hung83@gmail.com"
                    }
                }
            }
        }
    }
}
